# Generated by Django 5.1.3 on 2024-11-13 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('require_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('req_faculty', models.CharField(max_length=255)),
                ('req_major', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RecruitPost',
            fields=[
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='teamfinder_app.post')),
                ('tag', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResultPost',
            fields=[
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='teamfinder_app.post')),
                ('tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='teamfinder_app.post')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamfinder_app.requirement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='teamfinder_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('registration_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='teamfinder_app.post')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamfinder_app.request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamfinder_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('post_comment_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('reaction', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='teamfinder_app.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamfinder_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='teamfinder_app.user'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='teamfinder_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamfinder_app.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamfinder_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to='teamfinder_app.user'),
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='teamfinder_app.message')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_direct_messages', to='teamfinder_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='teamfinder_app.message')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='teamfinder_app.group')),
            ],
        ),
        migrations.AddField(
            model_name='requirement',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='teamfinder_app.recruitpost'),
        ),
    ]
