# Generated by Django 5.1.3 on 2024-11-23 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamfinder_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='teamfinder_app.team'),
            preserve_default=False,
        ),
    ]
