# Generated by Django 5.1.3 on 2024-11-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamfinder_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitpost',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
