# Generated by Django 5.1.3 on 2024-11-16 13:29

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('teamfinder_app', '0002_alter_recruitpost_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
                ('faculty', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
                ('major', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='req_faculty',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='req_major',
        ),
        migrations.AlterField(
            model_name='requirement',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name='FacultyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_tag', to='teamfinder_app.faculty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MajorTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_tag', to='teamfinder_app.major')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='requirement',
            name='req_faculty',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='teamfinder_app.FacultyTag', to='teamfinder_app.Faculty', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='req_major',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='teamfinder_app.MajorTag', to='teamfinder_app.Major', verbose_name='Tags'),
        ),
    ]
