# Generated by Django 5.1.3 on 2024-12-05 09:35

import teamfinder_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamfinder_app', '0002_feedback_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='fallback.png', null=True, upload_to='', validators=[teamfinder_app.validators.validate_file_size]),
        ),
    ]
