# Generated by Django 5.1.3 on 2024-12-08 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamfinder_app', '0003_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='amount',
        ),
    ]
