# Generated by Django 5.1.3 on 2024-11-14 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamfinder_app', '0003_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
