# Generated by Django 5.1.3 on 2024-11-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamfinder_app', '0004_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='year',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='requirement',
            name='year_max',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='requirement',
            name='year_min',
            field=models.IntegerField(default=1),
        ),
    ]
