# Generated by Django 5.1.3 on 2024-12-04 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_groupmessage_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='users_online',
        ),
    ]
